# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mePyGuis\guis\TracerEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(772, 312)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 3, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.title_tracer = QtGui.QLabel(Dialog)
        self.title_tracer.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.title_tracer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.title_tracer.setObjectName(_fromUtf8("title_tracer"))
        self.verticalLayout.addWidget(self.title_tracer)
        spacerItem1 = QtGui.QSpacerItem(0, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(90, 90, 90);\n"
"font: 7pt;"))
        self.label_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(200, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(3, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(3, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 3, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 2, 0, 1, 5)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 2, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 0, 0, 1, 5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.discardButton = QtGui.QPushButton(Dialog)
        self.discardButton.setObjectName(_fromUtf8("discardButton"))
        self.horizontalLayout.addWidget(self.discardButton)
        self.acceptButton = QtGui.QPushButton(Dialog)
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.horizontalLayout.addWidget(self.acceptButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 4, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 7, 0, 1, 1)
        self.tLabeledIsotopicPurity = QtGui.QDoubleSpinBox(Dialog)
        self.tLabeledIsotopicPurity.setProperty("value", 99.5)
        self.tLabeledIsotopicPurity.setObjectName(_fromUtf8("tLabeledIsotopicPurity"))
        self.gridLayout_3.addWidget(self.tLabeledIsotopicPurity, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.tNativeIsotopicPurity = QtGui.QDoubleSpinBox(Dialog)
        self.tNativeIsotopicPurity.setProperty("value", 98.97)
        self.tNativeIsotopicPurity.setObjectName(_fromUtf8("tNativeIsotopicPurity"))
        self.gridLayout_3.addWidget(self.tNativeIsotopicPurity, 2, 1, 1, 1)
        self.tName = QtGui.QLineEdit(Dialog)
        self.tName.setObjectName(_fromUtf8("tName"))
        self.gridLayout_3.addWidget(self.tName, 0, 1, 1, 1)
        self.tLabelingIsotopes = QtGui.QLineEdit(Dialog)
        self.tLabelingIsotopes.setObjectName(_fromUtf8("tLabelingIsotopes"))
        self.gridLayout_3.addWidget(self.tLabelingIsotopes, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.tRatio = QtGui.QLabel(Dialog)
        self.tRatio.setObjectName(_fromUtf8("tRatio"))
        self.gridLayout_3.addWidget(self.tRatio, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.tNativeAmount = QtGui.QDoubleSpinBox(Dialog)
        self.tNativeAmount.setMaximum(1000.0)
        self.tNativeAmount.setProperty("value", 500.0)
        self.tNativeAmount.setObjectName(_fromUtf8("tNativeAmount"))
        self.gridLayout_3.addWidget(self.tNativeAmount, 4, 1, 1, 1)
        self.tLabeledAmount = QtGui.QDoubleSpinBox(Dialog)
        self.tLabeledAmount.setMaximum(1000.0)
        self.tLabeledAmount.setProperty("value", 500.0)
        self.tLabeledAmount.setObjectName(_fromUtf8("tLabeledAmount"))
        self.gridLayout_3.addWidget(self.tLabeledAmount, 5, 1, 1, 1)
        self.tMinRatio = QtGui.QDoubleSpinBox(Dialog)
        self.tMinRatio.setMaximum(10000000.0)
        self.tMinRatio.setProperty("value", 62.5)
        self.tMinRatio.setObjectName(_fromUtf8("tMinRatio"))
        self.gridLayout_3.addWidget(self.tMinRatio, 7, 1, 1, 1)
        self.tMaxRatio = QtGui.QDoubleSpinBox(Dialog)
        self.tMaxRatio.setMaximum(1000000.0)
        self.tMaxRatio.setProperty("value", 160.0)
        self.tMaxRatio.setObjectName(_fromUtf8("tMaxRatio"))
        self.gridLayout_3.addWidget(self.tMaxRatio, 8, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 9, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "Actions", None))
        self.title_tracer.setText(_translate("Dialog", "Tracer", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Please specify the tracer used for the experiment</p><p><br/></p></body></html>", None))
        self.discardButton.setText(_translate("Dialog", "Discard", None))
        self.acceptButton.setText(_translate("Dialog", "Accept", None))
        self.label.setText(_translate("Dialog", "Tracer name", None))
        self.label_11.setText(_translate("Dialog", "Minimal ratio (%)", None))
        self.label_10.setText(_translate("Dialog", "Isotopic purity labeled (%)", None))
        self.tName.setText(_translate("Dialog", "DON", None))
        self.tLabelingIsotopes.setText(_translate("Dialog", "[13C]15", None))
        self.label_12.setText(_translate("Dialog", "Maximum ratio (%)", None))
        self.label_4.setText(_translate("Dialog", "Labeling isotopes", None))
        self.tRatio.setText(_translate("Dialog", "-", None))
        self.label_7.setText(_translate("Dialog", "Ratio", None))
        self.label_5.setText(_translate("Dialog", "Amount native", None))
        self.label_6.setText(_translate("Dialog", "Amount labeled", None))
        self.label_9.setText(_translate("Dialog", "Isotopic purity native (%)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

